name: bandera
description: A new Flutter project.

publish_to: 'none'

version: 7.0.0+7

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  social_media_flutter: ^0.0.2
  http: ^0.13.5
  youtube_player_flutter: ^8.1.2
  url_launcher: ^6.0.3
  flutter_native_splash: ^2.2.19
  comment_box: ^0.0.18

flutter_native_splash:
  android: true
  ios: true
  web: false
  background_image: "assets/universalbackground.jpg"
  image: "assets/bandera_musical_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Gajraj
      fonts:
        - asset: fonts/GajrajOne-Regular.ttf
    - family: Teko
      fonts:
        - asset: fonts/Teko-Light.ttf
        


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/bandera_musical_icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/bandera_musical_icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/bandera_musical_icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/bandera_musical_icon.png"
